//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiết_kiểm_kho
    {
        public int SL_hệ_thống { get; set; }
        public int SL_thực_tế { get; set; }
        public string ID_kiểm_kho { get; set; }
        public string ID_sản_phẩm { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual Sản_phẩm Sản_phẩm { get; set; }
    }
}
