//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiết_đơn_hàng
    {
        public int Số_lượng { get; set; }
        public Nullable<decimal> Thành_tiền { get; set; }
        public int ID_đơn_hàng { get; set; }
        public int ID_sản_phẩm { get; set; }
        public string ID_CTKM { get; set; }
    
        public virtual CTKM CTKM { get; set; }
        public virtual Đơn_mua_hàng Đơn_mua_hàng { get; set; }
        public virtual Sản_phẩm Sản_phẩm { get; set; }
    }
}
