//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kho()
        {
            this.Chi_tiết_kiểm_kho = new HashSet<Chi_tiết_kiểm_kho>();
            this.Nhân_viên = new HashSet<Nhân_viên>();
        }
    
        public string ID_kiểm_kho { get; set; }
        public System.DateTime Ngày { get; set; }
        public System.TimeSpan Giờ { get; set; }
        public string ID_nhân_viên { get; set; }
        public int Tổng_số_lượng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_kiểm_kho> Chi_tiết_kiểm_kho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhân_viên> Nhân_viên { get; set; }
    }
}
