//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khách_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khách_hàng()
        {
            this.Đơn_mua_hàng = new HashSet<Đơn_mua_hàng>();
        }
    
        public string ID_khách { get; set; }
        public string Tên_đăng_nhập { get; set; }
        public string Mật_khẩu { get; set; }
        public string Họ_tên { get; set; }
        public string Địa_chỉ { get; set; }
        public string Số_điện_thoại { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đơn_mua_hàng> Đơn_mua_hàng { get; set; }
    }
}
