//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mã_giảm_giá
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mã_giảm_giá()
        {
            this.Đơn_mua_hàng = new HashSet<Đơn_mua_hàng>();
        }
    
        public string ID_mã_giảm_giá { get; set; }
        public string Nội_dung { get; set; }
        public double Số_tiền_giảm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đơn_mua_hàng> Đơn_mua_hàng { get; set; }
    }
}
