//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_viên
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhân_viên()
        {
            this.Đơn_mua_hàng = new HashSet<Đơn_mua_hàng>();
        }
    
        public string ID_nhân_viên { get; set; }
        public string Họ_tên_nhân_viên { get; set; }
        public Nullable<int> Năm_sinh { get; set; }
        public Nullable<int> ID_chức_vụ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đơn_mua_hàng> Đơn_mua_hàng { get; set; }
    }
}
