//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_viên
    {
        public string ID_nhân_viên { get; set; }
        public string TK_nhân_viên { get; set; }
        public string MK_nhân_viên { get; set; }
        public string Họ_tên_nhân_viên { get; set; }
        public short Năm_sinh { get; set; }
        public string Chức_vụ { get; set; }
        public string ID_đơn_hàng { get; set; }
        public string ID_kiểm_kho { get; set; }
    
        public virtual Đơn_mua_hàng Đơn_mua_hàng { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
