//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Đơn_mua_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Đơn_mua_hàng()
        {
            this.Chi_tiết_đơn_hàng = new HashSet<Chi_tiết_đơn_hàng>();
            this.Nhân_viên = new HashSet<Nhân_viên>();
        }
    
        public string ID_đơn_hàng { get; set; }
        public short Số_lượng_sản_phẩm { get; set; }
        public decimal Tổng_thành_tiền { get; set; }
        public System.DateTime Ngày_lập_đơn { get; set; }
        public string Trạng_thái_đơn_hàng { get; set; }
        public string Họ_tên_người_nhận { get; set; }
        public string SĐT_người_nhận { get; set; }
        public string Địa_chỉ_người_nhận { get; set; }
        public string ID_mã_giảm_giá { get; set; }
        public string ID_khách { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiết_đơn_hàng> Chi_tiết_đơn_hàng { get; set; }
        public virtual Khách_hàng Khách_hàng { get; set; }
        public virtual Mã_giảm_giá Mã_giảm_giá { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhân_viên> Nhân_viên { get; set; }
    }
}
